//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIETFRUIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_HOA_DON
    {
        public string MA_HOA_DON { get; set; }
        public string MA_SAN_PHAM { get; set; }
        public double KHOI_LUONG { get; set; }
        public double DON_GIA { get; set; }
        public double THANH_TIEN { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual KHO_SAN_PHAM KHO_SAN_PHAM { get; set; }
    }
}
