//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIETFRUIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUC_NANG
    {
        public CHUC_NANG()
        {
            this.TRANG_THAI = new HashSet<TRANG_THAI>();
        }
    
        public string MA_CHUC_NANG { get; set; }
        public string TEN_CHUC_NANG { get; set; }
    
        public virtual ICollection<TRANG_THAI> TRANG_THAI { get; set; }
    }
}
