//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIETFRUIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIO_LAM
    {
        public string MA_NHAN_VIEN { get; set; }
        public string MA_GiO_LAM { get; set; }
        public Nullable<System.DateTime> NGAY_LAM { get; set; }
        public Nullable<double> GIO_LAM1 { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
