//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIETFRUIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO_SAN_PHAM
    {
        public KHO_SAN_PHAM()
        {
            this.CHI_TIET_HOA_DON = new HashSet<CHI_TIET_HOA_DON>();
        }
    
        public string MA_SAN_PHAM { get; set; }
        public string TEN_SAN_PHAM { get; set; }
        public double KHOI_LUONG_NHAP { get; set; }
        public double GIA_NHAP_VAO { get; set; }
        public double GIA_BAN_RA { get; set; }
        public System.DateTime NGAY_DONG_GOI { get; set; }
        public System.DateTime NGAY_HET_HAN { get; set; }
        public string NHA_CUNG_CAP { get; set; }
        public string NOI_XUAT_XU { get; set; }
        public byte[] ANH { get; set; }
    
        public virtual ICollection<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
    }
}
