//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIETFRUIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANG_THAI
    {
        public string TEN_TAI_KHOAN { get; set; }
        public string MA_CHUC_NANG { get; set; }
        public Nullable<bool> TRANG_THAI1 { get; set; }
    
        public virtual CHUC_NANG CHUC_NANG { get; set; }
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
    }
}
